services:
  php:
    container_name: enceladus-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www
    networks:
      - enceladus_network
  
  nginx:
    container_name: enceladus-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - enceladus_network
  
  postgres:
    container_name: enceladus-postgres
    image: postgres:alpine
    restart: always
    volumes:
      - enceladus_psql_data:/var/lib/postgresql/data:rw
    networks:
      - enceladus_network
    ports:
      - '5432:5432'
    environment:
      # POSTGRES_DB: enceladus
      # POSTGRES_PASSWORD: enceladus
      # POSTGRES_USER: enceladus
      POSTGRES_URL: ${DATABASE_URL}

networks:
  enceladus_network:
    driver: bridge

volumes:
  enceladus_psql_data:
